---
root: true

plugins:
  - jest
  - babel
  - "@html-eslint"

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  "@html-eslint/indent":
    - "error"
    - 2


overrides:
  - files: "*.html"
    parser: "@html-eslint/parser"
    extends:
      - "plugin:@html-eslint/recommended"
  - files: "*.html"
    rules:
      max-len: off
